-- Weekly e-mail reminder (SMTP settings per tenant, e-mail per user) and help-video links.
ALTER TABLE "Tenant" ADD COLUMN "smtpHost" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Tenant" ADD COLUMN "smtpPort" INTEGER NOT NULL DEFAULT 587;
ALTER TABLE "Tenant" ADD COLUMN "smtpUser" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Tenant" ADD COLUMN "smtpPass" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Tenant" ADD COLUMN "smtpFrom" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Tenant" ADD COLUMN "digestOn" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tenant" ADD COLUMN "digestDay" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Tenant" ADD COLUMN "digestHour" INTEGER NOT NULL DEFAULT 7;
ALTER TABLE "Tenant" ADD COLUMN "lastDigest" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Tenant" ADD COLUMN "helpVideos" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "User" ADD COLUMN "email" TEXT NOT NULL DEFAULT '';
